### ISSUE TITLE
Sometimes the place is closed

### ISSUE THREAD

**Issue by PortNumber53** [ctrlaltdev/wheretoeat#1]
There are days, the selected place is open, wheretoeat should integrate with third party services to figure that out.

**Comment by ctrlaltdev** [comment]
Thank you for your feedback.

Here, at ctrlaltdev, take users satisfaction very seriously.
That's why a customer representative will get back to you to collect your exact view on that matter.

Please note that the average response time is 5382 days.
In the meanwhile, we encourage you to actually do some work and make a pull-request.

This message is not automated, it has been crafted by one of our unpaid intern that only survive on tips.
Please remember to tip the intern unless you have no heart.
