### ISSUE TITLE
Calendar integration

### ISSUE THREAD

**Issue by PortNumber53** [ctrlaltdev/wheretoeat#2]
wheretoeat should integrate with participant's calendars to know, for instance, when there's a planned outing and output that place instead of picking another one

**Comment by ctrlaltdev** [comment]
Thank you for your feedback.

Here, at ctrlaltdev, take users satisfaction very seriously.
That's why a customer representative will get back to you to collect your exact view on that matter.

Please note that the average response time is 5382 days.
In the meanwhile, we encourage you to actually do some work and make a pull-request.

This message is not automated, it has been crafted by one of our unpaid intern that only survive on tips.
Please remember to tip the intern unless you have no heart.
